# Generated by Django 4.0.4 on 2022-05-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='candidate_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('address', models.TextField()),
                ('course', models.CharField(max_length=25)),
                ('degree', models.CharField(max_length=25)),
                ('yoe', models.IntegerField()),
                ('last_company', models.CharField(max_length=30)),
                ('skills', models.TextField()),
                ('resume', models.FileField(upload_to='media')),
                ('status', models.CharField(max_length=25)),
            ],
        ),
    ]
