# Generated by Django 4.0.4 on 2022-05-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_last_company_candidate_info_pcompany_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate_info',
            name='phone',
            field=models.CharField(default=999, max_length=13),
            preserve_default=False,
        ),
    ]
