# Generated by Django 4.0.4 on 2022-05-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_candidate_info_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate_info',
            name='yoe',
            field=models.IntegerField(null=True),
        ),
    ]
